name: Dependabot Auto-merge

on:
  pull_request:
  push:
    branches:
      - develop

jobs:
  dependabot-auto-merge:
    if: github.event_name == 'pull_request' && github.actor == 'dependabot[bot]'
    permissions:
      contents: write
      pull-requests: write
      issues: write
    uses: winccoa-tools-pack/.github/.github/workflows/reusable-dependabot-auto-merge.yml@main
    secrets: inherit
    with:
      pr_url: ${{ github.event.pull_request.html_url }}
      approve_pr: true
      merge_method: squash
      update_branch: true

  dependabot-refresh:
    if: github.event_name == 'push' && github.ref_name == 'develop'
    permissions:
      contents: write
      pull-requests: write
      issues: write
    uses: winccoa-tools-pack/.github/.github/workflows/reusable-dependabot-refresh.yml@main
    secrets: inherit
    with:
      base_branch: develop
      merge_method: squash
      update_branch: true
      approve_prs: true
      enable_auto_merge: true
