name: Dependabot (create release PR)

on:
  pull_request:
    types:
      - closed
    branches:
      - develop
  workflow_dispatch:

jobs:
  create-release-pr:
    if: >-
      github.event_name == 'workflow_dispatch' ||
      (github.event.pull_request.merged == true && github.event.pull_request.user.login == 'dependabot[bot]')
    permissions:
      contents: write
      pull-requests: write
      issues: write
    uses: winccoa-tools-pack/.github/.github/workflows/reusable-dependabot-release-pr.yml@main
    secrets: inherit
    with:
      base_branch: develop
      target_branch: main
      enable_auto_merge: false
      project_type: npm
      auto_release: true
